### ISSUE TITLE
Brilliant

### ISSUE THREAD

**Issue by kocane** [talisto/plex-inotifier#1]
@talisto 

Ain't too big on github. Not sure how to let you know that I found the useful other than creating an issue.

Works great, exactly what I needed. My NAS has all my movies but Plex runs on a NUC and cannot detect library changes on the NFS mounts. Now I just hope inotify won't keep my disks spinning ;)

thanks

**Comment by talisto** [comment]
Great!!  I'm really happy to hear that it's working well for you! 😊

**Comment by kocane** [comment]
@talisto ;-) 

One thing I'm wondering though, not sure if it has any affect, but on certainl files (seemingly only .srt) I get this when a folder is updated (for instance):
```
Updating section ID 3
/storage/mediacenter/movies/Testament of Dr. Mabuse, The (1933)/Das.Testament.des.Dr..Mabuse.(Fritz.Lang,.1933).en.srt is not an allowed path
/storage/mediacenter/movies/Testament of Dr. Mabuse, The (1933)/Das.Testament.des.Dr..Mabuse.(Fritz.Lang,.1933).English.srt is not an allowed path
```
Permissions shouldn't be any different. Any idea why?

**Comment by talisto** [comment]
Most filesystems have a limit on how many files can be watched via inotify, so I've set the script to only watch known media filetypes.  I didn't include "srt" files in the watchlist, which is an oversight on my part.  At the top of the script you'll see an array variable called "allowed_exts", you can add "srt" to that list and it will then trigger a refresh when srt files are added or modified.

I'll update the script to include srt files in the future.

I should also probably fix that error message to be more specific about why the path isn't "allowed".

**Comment by kocane** [comment]
@talisto  nah I think the error msg is fine, it's just me who's clearly slow. Not sure how I missed the "allowed file extentions" section :p
