### ISSUE TITLE
enhancement to ignore @eaDir and @SynoEAStream created by some NAS indexing or Filesystem

### ISSUE THREAD

**Issue by roquint** [talisto/plex-inotifier#3]
great script, work perfectly as intended even in 2020 but at the first run the script was unable to detect some file addition or deletion in my libraries and each time it throws message like this : 
/volume2/Video/Movies/@eaDir/Mymovie.avi@SynoEAStream is not an                                                                                                                                                              allowed path

i get rid of this temporarily with this kind of command : 
 find /volume2 -type d -name "@eaDir" -exec rm -r \"{}\" \;

Adding some enhancement to ignore all this @eaDir and @SynoEAStream on the NAS filesystem would be great !

I think theses files and dirs were creating by activating AFP Shares on the synology but i'm not sure.

Thanks for your help.

Ps if needed i can help you if you need to translate the README in french.

**Comment by talisto** [comment]
Hi @luckypaste,

The "not an allowed path" messages are actually just info messages from the script, because it's specifically written to not watch @eaDir directories, so it's just informing you that it's skipping those directories.  You can disregard those messages, as they're not actually errors.

**Comment by talisto** [comment]
I'm going to close this issue; if you're still having problems with other file additions/deletions not being detected, make another issue and I'll look into it.
